FROM node:20.18

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Create uploads directory
RUN mkdir -p public/uploads

# Expose API port
EXPOSE 3000

# Command to run in development mode with nodemon for hot reloading
CMD ["npm", "run", "dev"]