// List of all 193 UN member states with names in English and Russian
const countries = [
    { name: { en: "Afghanistan", ru: "Афганистан" }, code: "AF" },
    { name: { en: "Albania", ru: "Албания" }, code: "AL" },
    { name: { en: "Algeria", ru: "Алжир" }, code: "DZ" },
    { name: { en: "Andorra", ru: "Андорра" }, code: "AD" },
    { name: { en: "Angola", ru: "Ангола" }, code: "AO" },
    { name: { en: "Antigua and Barbuda", ru: "Антигуа и Барбуда" }, code: "AG" },
    { name: { en: "Argentina", ru: "Аргентина" }, code: "AR" },
    { name: { en: "Armenia", ru: "Армения" }, code: "AM" },
    { name: { en: "Australia", ru: "Австралия" }, code: "AU" },
    { name: { en: "Austria", ru: "Австрия" }, code: "AT" },
    { name: { en: "Azerbaijan", ru: "Азербайджан" }, code: "AZ" },
    { name: { en: "Bahamas", ru: "Багамские Острова" }, code: "BS" },
    { name: { en: "Bahrain", ru: "Бахрейн" }, code: "BH" },
    { name: { en: "Bangladesh", ru: "Бангладеш" }, code: "BD" },
    { name: { en: "Barbados", ru: "Барбадос" }, code: "BB" },
    { name: { en: "Belarus", ru: "Беларусь" }, code: "BY" },
    { name: { en: "Belgium", ru: "Бельгия" }, code: "BE" },
    { name: { en: "Belize", ru: "Белиз" }, code: "BZ" },
    { name: { en: "Benin", ru: "Бенин" }, code: "BJ" },
    { name: { en: "Bhutan", ru: "Бутан" }, code: "BT" },
    { name: { en: "Bolivia", ru: "Боливия" }, code: "BO" },
    { name: { en: "Bosnia and Herzegovina", ru: "Босния и Герцеговина" }, code: "BA" },
    { name: { en: "Botswana", ru: "Ботсвана" }, code: "BW" },
    { name: { en: "Brazil", ru: "Бразилия" }, code: "BR" },
    { name: { en: "Brunei", ru: "Бруней" }, code: "BN" },
    { name: { en: "Bulgaria", ru: "Болгария" }, code: "BG" },
    { name: { en: "Burkina Faso", ru: "Буркина-Фасо" }, code: "BF" },
    { name: { en: "Burundi", ru: "Бурунди" }, code: "BI" },
    { name: { en: "Cabo Verde", ru: "Кабо-Верде" }, code: "CV" },
    { name: { en: "Cambodia", ru: "Камбоджа" }, code: "KH" },
    { name: { en: "Cameroon", ru: "Камерун" }, code: "CM" },
    { name: { en: "Canada", ru: "Канада" }, code: "CA" },
    { name: { en: "Central African Republic", ru: "Центральноафриканская Республика" }, code: "CF" },
    { name: { en: "Chad", ru: "Чад" }, code: "TD" },
    { name: { en: "Chile", ru: "Чили" }, code: "CL" },
    { name: { en: "China", ru: "Китай" }, code: "CN" },
    { name: { en: "Colombia", ru: "Колумбия" }, code: "CO" },
    { name: { en: "Comoros", ru: "Коморские Острова" }, code: "KM" },
    { name: { en: "Congo", ru: "Конго" }, code: "CG" },
    { name: { en: "Costa Rica", ru: "Коста-Рика" }, code: "CR" },
    { name: { en: "Cote d'Ivoire", ru: "Кот-д'Ивуар" }, code: "CI" },
    { name: { en: "Croatia", ru: "Хорватия" }, code: "HR" },
    { name: { en: "Cuba", ru: "Куба" }, code: "CU" },
    { name: { en: "Cyprus", ru: "Кипр" }, code: "CY" },
    { name: { en: "Czech Republic", ru: "Чехия" }, code: "CZ" },
    { name: { en: "Democratic People's Republic of Korea", ru: "Корейская Народно-Демократическая Республика" }, code: "KP" },
    { name: { en: "Democratic Republic of the Congo", ru: "Демократическая Республика Конго" }, code: "CD" },
    { name: { en: "Denmark", ru: "Дания" }, code: "DK" },
    { name: { en: "Djibouti", ru: "Джибути" }, code: "DJ" },
    { name: { en: "Dominica", ru: "Доминика" }, code: "DM" },
    { name: { en: "Dominican Republic", ru: "Доминиканская Республика" }, code: "DO" },
    { name: { en: "Ecuador", ru: "Эквадор" }, code: "EC" },
    { name: { en: "Egypt", ru: "Египет" }, code: "EG" },
    { name: { en: "El Salvador", ru: "Сальвадор" }, code: "SV" },
    { name: { en: "Equatorial Guinea", ru: "Экваториальная Гвинея" }, code: "GQ" },
    { name: { en: "Eritrea", ru: "Эритрея" }, code: "ER" },
    { name: { en: "Estonia", ru: "Эстония" }, code: "EE" },
    { name: { en: "Eswatini", ru: "Эсватини" }, code: "SZ" },
    { name: { en: "Ethiopia", ru: "Эфиопия" }, code: "ET" },
    { name: { en: "Fiji", ru: "Фиджи" }, code: "FJ" },
    { name: { en: "Finland", ru: "Финляндия" }, code: "FI" },
    { name: { en: "France", ru: "Франция" }, code: "FR" },
    { name: { en: "Gabon", ru: "Габон" }, code: "GA" },
    { name: { en: "Gambia", ru: "Гамбия" }, code: "GM" },
    { name: { en: "Georgia", ru: "Грузия" }, code: "GE" },
    { name: { en: "Germany", ru: "Германия" }, code: "DE" },
    { name: { en: "Ghana", ru: "Гана" }, code: "GH" },
    { name: { en: "Greece", ru: "Греция" }, code: "GR" },
    { name: { en: "Grenada", ru: "Гренада" }, code: "GD" },
    { name: { en: "Guatemala", ru: "Гватемала" }, code: "GT" },
    { name: { en: "Guinea", ru: "Гвинея" }, code: "GN" },
    { name: { en: "Guinea-Bissau", ru: "Гвинея-Бисау" }, code: "GW" },
    { name: { en: "Guyana", ru: "Гайана" }, code: "GY" },
    { name: { en: "Haiti", ru: "Гаити" }, code: "HT" },
    { name: { en: "Honduras", ru: "Гондурас" }, code: "HN" },
    { name: { en: "Hungary", ru: "Венгрия" }, code: "HU" },
    { name: { en: "Iceland", ru: "Исландия" }, code: "IS" },
    { name: { en: "India", ru: "Индия" }, code: "IN" },
    { name: { en: "Indonesia", ru: "Индонезия" }, code: "ID" },
    { name: { en: "Iran", ru: "Иран" }, code: "IR" },
    { name: { en: "Iraq", ru: "Ирак" }, code: "IQ" },
    { name: { en: "Ireland", ru: "Ирландия" }, code: "IE" },
    { name: { en: "Israel", ru: "Израиль" }, code: "IL" },
    { name: { en: "Italy", ru: "Италия" }, code: "IT" },
    { name: { en: "Jamaica", ru: "Ямайка" }, code: "JM" },
    { name: { en: "Japan", ru: "Япония" }, code: "JP" },
    { name: { en: "Jordan", ru: "Иордания" }, code: "JO" },
    { name: { en: "Kazakhstan", ru: "Казахстан" }, code: "KZ" },
    { name: { en: "Kenya", ru: "Кения" }, code: "KE" },
    { name: { en: "Kiribati", ru: "Кирибати" }, code: "KI" },
    { name: { en: "Kuwait", ru: "Кувейт" }, code: "KW" },
    { name: { en: "Kyrgyzstan", ru: "Кыргызстан" }, code: "KG" },
    { name: { en: "Lao People's Democratic Republic", ru: "Лаосская Народно-Демократическая Республика" }, code: "LA" },
    { name: { en: "Latvia", ru: "Латвия" }, code: "LV" },
    { name: { en: "Lebanon", ru: "Ливан" }, code: "LB" },
    { name: { en: "Lesotho", ru: "Лесото" }, code: "LS" },
    { name: { en: "Liberia", ru: "Либерия" }, code: "LR" },
    { name: { en: "Libya", ru: "Ливия" }, code: "LY" },
    { name: { en: "Liechtenstein", ru: "Лихтенштейн" }, code: "LI" },
    { name: { en: "Lithuania", ru: "Литва" }, code: "LT" },
    { name: { en: "Luxembourg", ru: "Люксембург" }, code: "LU" },
    { name: { en: "Madagascar", ru: "Мадагаскар" }, code: "MG" },
    { name: { en: "Malawi", ru: "Малави" }, code: "MW" },
    { name: { en: "Malaysia", ru: "Малайзия" }, code: "MY" },
    { name: { en: "Maldives", ru: "Мальдивы" }, code: "MV" },
    { name: { en: "Mali", ru: "Мали" }, code: "ML" },
    { name: { en: "Malta", ru: "Мальта" }, code: "MT" },
    { name: { en: "Marshall Islands", ru: "Маршалловы Острова" }, code: "MH" },
    { name: { en: "Mauritania", ru: "Мавритания" }, code: "MR" },
    { name: { en: "Mauritius", ru: "Маврикий" }, code: "MU" },
    { name: { en: "Mexico", ru: "Мексика" }, code: "MX" },
    { name: { en: "Micronesia", ru: "Микронезия" }, code: "FM" },
    { name: { en: "Monaco", ru: "Монако" }, code: "MC" },
    { name: { en: "Mongolia", ru: "Монголия" }, code: "MN" },
    { name: { en: "Montenegro", ru: "Черногория" }, code: "ME" },
    { name: { en: "Morocco", ru: "Марокко" }, code: "MA" },
    { name: { en: "Mozambique", ru: "Мозамбик" }, code: "MZ" },
    { name: { en: "Myanmar", ru: "Мьянма" }, code: "MM" },
    { name: { en: "Namibia", ru: "Намибия" }, code: "NA" },
    { name: { en: "Nauru", ru: "Науру" }, code: "NR" },
    { name: { en: "Nepal", ru: "Непал" }, code: "NP" },
    { name: { en: "Netherlands", ru: "Нидерланды" }, code: "NL" },
    { name: { en: "New Zealand", ru: "Новая Зеландия" }, code: "NZ" },
    { name: { en: "Nicaragua", ru: "Никарагуа" }, code: "NI" },
    { name: { en: "Niger", ru: "Нигер" }, code: "NE" },
    { name: { en: "Nigeria", ru: "Нигерия" }, code: "NG" },
    { name: { en: "North Macedonia", ru: "Северная Македония" }, code: "MK" },
    { name: { en: "Norway", ru: "Норвегия" }, code: "NO" },
    { name: { en: "Oman", ru: "Оман" }, code: "OM" },
    { name: { en: "Pakistan", ru: "Пакистан" }, code: "PK" },
    { name: { en: "Palau", ru: "Палау" }, code: "PW" },
    { name: { en: "Panama", ru: "Панама" }, code: "PA" },
    { name: { en: "Papua New Guinea", ru: "Папуа-Новая Гвинея" }, code: "PG" },
    { name: { en: "Paraguay", ru: "Парагвай" }, code: "PY" },
    { name: { en: "Peru", ru: "Перу" }, code: "PE" },
    { name: { en: "Philippines", ru: "Филиппины" }, code: "PH" },
    { name: { en: "Poland", ru: "Польша" }, code: "PL" },
    { name: { en: "Portugal", ru: "Португалия" }, code: "PT" },
    { name: { en: "Qatar", ru: "Катар" }, code: "QA" },
    { name: { en: "Republic of Korea", ru: "Республика Корея" }, code: "KR" },
    { name: { en: "Republic of Moldova", ru: "Республика Молдова" }, code: "MD" },
    { name: { en: "Romania", ru: "Румыния" }, code: "RO" },
    { name: { en: "Russian Federation", ru: "Российская Федерация" }, code: "RU" },
    { name: { en: "Rwanda", ru: "Руанда" }, code: "RW" },
    { name: { en: "Saint Kitts and Nevis", ru: "Сент-Китс и Невис" }, code: "KN" },
    { name: { en: "Saint Lucia", ru: "Сент-Люсия" }, code: "LC" },
    { name: { en: "Saint Vincent and the Grenadines", ru: "Сент-Винсент и Гренадины" }, code: "VC" },
    { name: { en: "Samoa", ru: "Самоа" }, code: "WS" },
    { name: { en: "San Marino", ru: "Сан-Марино" }, code: "SM" },
    { name: { en: "Sao Tome and Principe", ru: "Сан-Томе и Принсипи" }, code: "ST" },
    { name: { en: "Saudi Arabia", ru: "Саудовская Аравия" }, code: "SA" },
    { name: { en: "Senegal", ru: "Сенегал" }, code: "SN" },
    { name: { en: "Serbia", ru: "Сербия" }, code: "RS" },
    { name: { en: "Seychelles", ru: "Сейшельские Острова" }, code: "SC" },
    { name: { en: "Sierra Leone", ru: "Сьерра-Леоне" }, code: "SL" },
    { name: { en: "Singapore", ru: "Сингапур" }, code: "SG" },
    { name: { en: "Slovakia", ru: "Словакия" }, code: "SK" },
    { name: { en: "Slovenia", ru: "Словения" }, code: "SI" },
    { name: { en: "Solomon Islands", ru: "Соломоновы Острова" }, code: "SB" },
    { name: { en: "Somalia", ru: "Сомали" }, code: "SO" },
    { name: { en: "South Africa", ru: "Южная Африка" }, code: "ZA" },
    { name: { en: "South Sudan", ru: "Южный Судан" }, code: "SS" },
    { name: { en: "Spain", ru: "Испания" }, code: "ES" },
    { name: { en: "Sri Lanka", ru: "Шри-Ланка" }, code: "LK" },
    { name: { en: "Sudan", ru: "Судан" }, code: "SD" },
    { name: { en: "Suriname", ru: "Суринам" }, code: "SR" },
    { name: { en: "Sweden", ru: "Швеция" }, code: "SE" },
    { name: { en: "Switzerland", ru: "Швейцария" }, code: "CH" },
    { name: { en: "Syrian Arab Republic", ru: "Сирийская Арабская Республика" }, code: "SY" },
    { name: { en: "Tajikistan", ru: "Таджикистан" }, code: "TJ" },
    { name: { en: "Thailand", ru: "Таиланд" }, code: "TH" },
    { name: { en: "Timor-Leste", ru: "Тимор-Лешти" }, code: "TL" },
    { name: { en: "Togo", ru: "Того" }, code: "TG" },
    { name: { en: "Tonga", ru: "Тонга" }, code: "TO" },
    { name: { en: "Trinidad and Tobago", ru: "Тринидад и Тобаго" }, code: "TT" },
    { name: { en: "Tunisia", ru: "Тунис" }, code: "TN" },
    { name: { en: "Turkey", ru: "Турция" }, code: "TR" },
    { name: { en: "Turkmenistan", ru: "Туркменистан" }, code: "TM" },
    { name: { en: "Tuvalu", ru: "Тувалу" }, code: "TV" },
    { name: { en: "Uganda", ru: "Уганда" }, code: "UG" },
    { name: { en: "Ukraine", ru: "Украина" }, code: "UA" },
    { name: { en: "United Arab Emirates", ru: "Объединенные Арабские Эмираты" }, code: "AE" },
    { name: { en: "United Kingdom", ru: "Соединенное Королевство" }, code: "GB" },
    { name: { en: "United Republic of Tanzania", ru: "Объединенная Республика Танзания" }, code: "TZ" },
    { name: { en: "United States of America", ru: "Соединенные Штаты Америки" }, code: "US" },
    { name: { en: "Uruguay", ru: "Уругвай" }, code: "UY" },
    { name: { en: "Uzbekistan", ru: "Узбекистан" }, code: "UZ" },
    { name: { en: "Vanuatu", ru: "Вануату" }, code: "VU" },
    { name: { en: "Venezuela", ru: "Венесуэла" }, code: "VE" },
    { name: { en: "Viet Nam", ru: "Вьетнам" }, code: "VN" },
    { name: { en: "Yemen", ru: "Йемен" }, code: "YE" },
    { name: { en: "Zambia", ru: "Замбия" }, code: "ZM" },
    { name: { en: "Zimbabwe", ru: "Зимбабве" }, code: "ZW" }
];

module.exports = countries;